// HTTP routes: /sh, /api/*, /connector.py, /health.
// No auth required. Machine IDs use hostname_random to prevent conflicts.

import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { z } from "zod";
import { dispatchToolCall } from "./connector-ws.ts";
import type { Store } from "./store.ts";
import type { PendingCall, ToolResultFrame } from "./types.ts";
import { parseToolName, safeLabel } from "./util.ts";

const INSTALL_SCRIPT_TEMPLATE = [
	"#!/bin/sh",
	"# omp-teleport connector installer",
	"# Auto-generated by relay; do not edit.",
	"set -e",
	"",
	'RELAY_HTTP="__RELAY_HTTP__"',
	'RELAY_WS="__RELAY_WS__"',
	'INSTALL_DIR="${OMP_REMOTE_INSTALL_DIR:-$HOME/.omp-teleport}"',
	"",
	'mkdir -p "$INSTALL_DIR"',
	"",
	"# Persist config for re-runs",
	'cat > "$INSTALL_DIR/env" <<EOF',
	"OMP_REMOTE_RELAY=$RELAY_WS",
	"EOF",
	'[ -n "$OMP_REMOTE_LABEL" ] && echo "OMP_REMOTE_LABEL=$OMP_REMOTE_LABEL" >> "$INSTALL_DIR/env"',
	'chmod 600 "$INSTALL_DIR/env"',
	"",
	"# Pick a runtime: prefer python3",
	'if command -v python3 >/dev/null 2>&1; then',
	'    curl -fsSL "$RELAY_HTTP/connector.py" -o "$INSTALL_DIR/connector.py"',
	'    chmod +x "$INSTALL_DIR/connector.py"',
	'    if [ -f "$INSTALL_DIR/connector.pid" ] && kill -0 "$(cat "$INSTALL_DIR/connector.pid")" 2>/dev/null; then',
	'        echo "connector already running (pid $(cat "$INSTALL_DIR/connector.pid"))"',
	"        exit 0",
	"    fi",
	"    nohup python3 \"$INSTALL_DIR/connector.py\" \\",
	'        --relay "$RELAY_WS" \\',
	'        --install-dir "$INSTALL_DIR" \\',
	'>"$INSTALL_DIR/connector.log" 2>&1 &',
	'    echo $! > "$INSTALL_DIR/connector.pid"',
	'    echo "started omp-teleport connector (pid $!) in $INSTALL_DIR"',
	'    echo "tail -f $INSTALL_DIR/connector.log to see output"',
	"elif command -v python >/dev/null 2>&1; then",
	"    PY=python",
	'    curl -fsSL "$RELAY_HTTP/connector.py" -o "$INSTALL_DIR/connector.py"',
	'    nohup "$PY" "$INSTALL_DIR/connector.py" \\',
	'        --relay "$RELAY_WS" \\',
	'        --install-dir "$INSTALL_DIR" \\',
	'>"$INSTALL_DIR/connector.log" 2>&1 &',
	'    echo $! > "$INSTALL_DIR/connector.pid"',
	'    echo "started omp-teleport connector (pid $!) in $INSTALL_DIR"',
	"else",
	'    echo "ERROR: python3 (or python) is required but was not found on PATH" >&2',
	'    echo "Install Python 3 and re-run this command." >&2',
	"    exit 1",
	"fi",
	"",
].join("\n");

const INSTALL_SCRIPT_PS1_TEMPLATE = [
	'# omp-teleport connector installer (Windows)',
	'# Auto-generated by relay; do not edit.',
	'',
	'param(',
	'    [string]$Relay,',
	'    [string]$Label',
	')',
	'',
	'$ErrorActionPreference = "Stop"',
	'',
	'# Relay URLs (will be replaced by relay)',
	'RELAY_HTTP = "__RELAY_HTTP__"',
	'RELAY_WS = "__RELAY_WS__"',
	'',
	'if ($Relay) {',
	'    $RELAY_WS = $Relay',
	'    $RELAY_HTTP = $Relay -replace \'^ws\', \'http\',
	'}',
	'',
	'$INSTALL_DIR = if ($env:OMP_REMOTE_INSTALL_DIR) { $env:OMP_REMOTE_INSTALL_DIR } else { "$env:USERPROFILE\\.omp-teleport" }',
	'',
	'# Create install directory',
	'if (!(Test-Path $INSTALL_DIR)) {',
	'    New-Item -ItemType Directory -Path $INSTALL_DIR -Force | Out-Null',
	'}',
	'',
	'# Persist config',
	'$envContent = "OMP_REMOTE_RELAY=$RELAY_WS"',
	'if ($Label) {',
	'    $envContent += "\`nOMP_REMOTE_LABEL=$Label"',
	'}',
	'Set-Content -Path "$INSTALL_DIR\\env" -Value $envContent',
	'',
	'# Find Python',
	'$pythonCmd = $null',
	'$pythonFound = $false',
	'',
	'# Check for python3 first',
	'if (Get-Command python3 -ErrorAction SilentlyContinue) {',
	'    $pythonCmd = "python3"',
	'    $pythonFound = $true',
	'}',
	'# Check for python',
	'elseif (Get-Command python -ErrorAction SilentlyContinue) {',
	'    $pythonCmd = "python"',
	'    $pythonFound = $true',
	'}',
	'# Check for py launcher',
	'elseif (Get-Command py -ErrorAction SilentlyContinue) {',
	'    $pythonCmd = "py"',
	'    $pythonFound = $true',
	'}',
	'',
	'if (!$pythonFound) {',
	'    Write-Host "Python not found. Installing portable Python..." -ForegroundColor Yellow',
	'    ',
	'    # Download portable Python',
	'    $pythonUrl = "https://www.python.org/ftp/python/3.12.4/python-3.12.4-embed-amd64.zip"',
	'    $pythonZip = "$INSTALL_DIR\\python.zip"',
	'    $pythonDir = "$INSTALL_DIR\\python"',
	'    ',
	'    Write-Host "Downloading Python 3.12.4..."',
	'    Invoke-WebRequest -Uri $pythonUrl -OutFile $pythonZip',
	'    ',
	'    Write-Host "Extracting Python..."',
	'    Expand-Archive -Path $pythonZip -DestinationPath $pythonDir -Force',
	'    Remove-Item $pythonZip',
	'    ',
	'    # Add to PATH for this session',
	'    $env:PATH = "$pythonDir;$env:PATH"',
	'    $pythonCmd = "$pythonDir\\python.exe"',
	'    ',
	'    # Enable pip',
	'    $pthFile = "$pythonDir\\python312._pth"',
	'    if (Test-Path $pthFile) {',
	'        (Get-Content $pthFile) -replace \'#import site\', \'import site\' | Set-Content $pthFile',
	'    }',
	'    ',
	'    Write-Host "Python installed to $pythonDir"',
	'}',
	'',
	'# Download connector',
	'$connectorUrl = "$RELAY_HTTP/connector.py"',
	'$connectorPath = "$INSTALL_DIR\\connector.py"',
	'',
	'Write-Host "Downloading connector..."',
	'Invoke-WebRequest -Uri $connectorUrl -OutFile $connectorPath',
	'',
	'# Check if connector is already running',
	'$pidFile = "$INSTALL_DIR\\connector.pid"',
	'if (Test-Path $pidFile) {',
	'    $pid = Get-Content $pidFile',
	'    $process = Get-Process -Id $pid -ErrorAction SilentlyContinue',
	'    if ($process) {',
	'        Write-Host "Connector already running (PID $pid)"',
	'        exit 0',
	'    }',
	'}',
	'',
	'# Start connector',
	'Write-Host "Starting connector..."',
	'$processInfo = New-Object System.Diagnostics.ProcessStartInfo',
	'$processInfo.FileName = $pythonCmd',
	'$processInfo.Arguments = "\`"$connectorPath\`" --relay \`"$RELAY_WS\`" --install-dir \`"$INSTALL_DIR\`""',
	'$processInfo.UseShellExecute = $false',
	'$processInfo.RedirectStandardOutput = $true',
	'$processInfo.RedirectStandardError = $true',
	'$processInfo.CreateNoWindow = $true',
	'',
	'$process = [System.Diagnostics.Process]::Start($processInfo)',
	'$process.Id | Out-File -FilePath $pidFile',
	'',
	'Write-Host "Connector started (PID $($process.Id))"',
	'Write-Host "Install directory: $INSTALL_DIR"',
	'',
	'# Wait a bit to see if it starts successfully',
	'Start-Sleep -Seconds 2',
	'if ($process.HasExited) {',
	'    Write-Host "Connector failed to start!" -ForegroundColor Red',
	'    exit 1',
	'}',
	'',
	'Write-Host "Connector is running!" -ForegroundColor Green',
	'Write-Host "To stop: Stop-Process -Id $($process.Id)"',
].join("\n");


const INSTALL_SCRIPT_PS1_TEMPLATE = [
	'# omp-teleport connector installer (Windows)',
	'# Auto-generated by relay; do not edit.',
	'',
	'param(',
	'    [string]$Relay,',
	'    [string]$Label',
	')',
	'',
	'$ErrorActionPreference = "Stop"',
	'',
	'# Relay URLs (will be replaced by relay)',
	'RELAY_HTTP = "__RELAY_HTTP__"',
	'RELAY_WS = "__RELAY_WS__"',
	'',
	'if ($Relay) {',
	'    $RELAY_WS = $Relay',
	'    $RELAY_HTTP = $Relay -replace '"'"^ws"'"', '"'"http"'"'',
	'}',
	'',
	'$INSTALL_DIR = if ($env:OMP_REMOTE_INSTALL_DIR) { $env:OMP_REMOTE_INSTALL_DIR } else { "$env:USERPROFILE\.omp-teleport" }',
	'',
	'# Create install directory',
	'if (!(Test-Path $INSTALL_DIR)) {',
	'    New-Item -ItemType Directory -Path $INSTALL_DIR -Force | Out-Null',
	'}',
	'',
	'# Persist config',
	'$envContent = "OMP_REMOTE_RELAY=$RELAY_WS"',
	'if ($Label) {',
	'    $envContent += "`nOMP_REMOTE_LABEL=$Label"',
	'}',
	'Set-Content -Path "$INSTALL_DIR\env" -Value $envContent',
	'',
	'# Find Python',
	'$pythonCmd = $null',
	'$pythonFound = $false',
	'',
	'# Check for python3 first',
	'if (Get-Command python3 -ErrorAction SilentlyContinue) {',
	'    $pythonCmd = "python3"',
	'    $pythonFound = $true',
	'}',
	'# Check for python',
	'elseif (Get-Command python -ErrorAction SilentlyContinue) {',
	'    $pythonCmd = "python"',
	'    $pythonFound = $true',
	'}',
	'# Check for py launcher',
	'elseif (Get-Command py -ErrorAction SilentlyContinue) {',
	'    $pythonCmd = "py"',
	'    $pythonFound = $true',
	'}',
	'',
	'if (!$pythonFound) {',
	'    Write-Host "Python not found. Installing portable Python..." -ForegroundColor Yellow',
	'    ',
	'    # Download portable Python',
	'    $pythonUrl = "https://www.python.org/ftp/python/3.12.4/python-3.12.4-embed-amd64.zip"',
	'    $pythonZip = "$INSTALL_DIR\python.zip"',
	'    $pythonDir = "$INSTALL_DIR\python"',
	'    ',
	'    Write-Host "Downloading Python 3.12.4..."',
	'    Invoke-WebRequest -Uri $pythonUrl -OutFile $pythonZip',
	'    ',
	'    Write-Host "Extracting Python..."',
	'    Expand-Archive -Path $pythonZip -DestinationPath $pythonDir -Force',
	'    Remove-Item $pythonZip',
	'    ',
	'    # Add to PATH for this session',
	'    $env:PATH = "$pythonDir;$env:PATH"',
	'    $pythonCmd = "$pythonDir\python.exe"',
	'    ',
	'    # Enable pip',
	'    $pthFile = "$pythonDir\python312._pth"',
	'    if (Test-Path $pthFile) {',
	'        (Get-Content $pthFile) -replace '"'"#import

const ToolCallBody = z.object({
	name: z.string().min(1).max(256),
	arguments: z.record(z.unknown()).optional(),
	timeout_ms: z.number().int().min(1).max(3600_000).optional(),
	stream: z.boolean().optional(),
});

export interface RelayConfig {
	publicUrl: string;
}

function jsonResponse(data: unknown, status = 200, extraHeaders: Record<string, string> = {}): Response {
	return new Response(JSON.stringify(data), {
		status,
		headers: { "Content-Type": "application/json", ...extraHeaders },
	});
}

function derivePublicBase(req: Request): string {
	const url = new URL(req.url);
	return `${url.protocol}//${url.host}`;
}

function deriveWsBase(httpBase: string): string {
	return httpBase.replace(/^http/, "ws");
}

function renderInstallScript(httpBase: string): string {
	const wsBase = deriveWsBase(httpBase);
	return INSTALL_SCRIPT_TEMPLATE
		.replace(/__RELAY_HTTP__/g, httpBase)
		.replace(/__RELAY_WS__/g, `${wsBase}/ws/connector`);
}

function renderInstallScriptPs1(httpBase: string): string {
	const wsBase = deriveWsBase(httpBase);
	return INSTALL_SCRIPT_PS1_TEMPLATE
		.replace(/__RELAY_HTTP__/g, httpBase)
		.replace(/__RELAY_WS__/g, `${wsBase}/ws/connector`);
}

function readConnectorPy(): string | undefined {
	const candidates = [
		resolve(import.meta.dir, "..", "..", "connector", "connector.py"),
		resolve(import.meta.dir, "..", "connector.py"),
		resolve(process.cwd(), "connector", "connector.py"),
		resolve(process.cwd(), "connector.py"),
	];
	for (const c of candidates) {
		if (existsSync(c)) return readFileSync(c, "utf8");
	}
	return undefined;
}

export async function handleHttpRequest(req: Request, store: Store, cfg: RelayConfig): Promise<Response> {
	const url = new URL(req.url);

	if (url.pathname === "/sh" && req.method === "GET") {
		const base = cfg.publicUrl || derivePublicBase(req);
		const body = renderInstallScript(base);
		return new Response(body, {
			headers: {
				"Content-Type": "text/x-shellscript; charset=utf-8",
				"Content-Disposition": "inline; filename=install.sh",
			},
		});
	}
	
	if (url.pathname === "/psh" && req.method === "GET") {
		const base = cfg.publicUrl || derivePublicBase(req);
		const body = renderInstallScriptPs1(base);
		return new Response(body, {
			headers: {
				"Content-Type": "text/plain; charset=utf-8",
				"Content-Disposition": "inline; filename=install.ps1",
			},
		});
	}
	if (url.pathname === "/connector.py" && req.method === "GET") {
		const body = readConnectorPy();
		if (!body) return new Response("connector.py not found on server", { status: 500 });
		return new Response(body, {
			headers: { "Content-Type": "text/x-python; charset=utf-8" },
		});
	}

	if (url.pathname === "/health" && req.method === "GET") {
		return jsonResponse({ ok: true, machines: store.listMachines().length, online: store.listOnlineMachines().length });
	}

	if (url.pathname.startsWith("/api/")) {
		return handleApi(req, store, cfg);
	}

	return new Response("not found", { status: 404 });
}

async function handleApi(req: Request, store: Store, cfg: RelayConfig): Promise<Response> {
	const url = new URL(req.url);

	if (url.pathname === "/api/tools/call" && req.method === "POST") {
		return handleToolCall(req, store, cfg);
	}

	if (url.pathname === "/api/machines" && req.method === "GET") {
		const machines = store.listMachines().map((m) => ({
			id: m.id,
			label: m.label,
			hostname: m.hostname,
			os: m.os,
			arch: m.arch,
			version: m.version,
			connected_at: m.connected_at,
			last_seen_at: m.last_seen_at,
			status: m.status,
			capabilities: m.capabilities,
		}));
		return jsonResponse({ machines });
	}

	if (url.pathname === "/api/events" && req.method === "GET") {
		return handleEventsStream(req, store);
	}

	return new Response("not found", { status: 404 });
}

async function handleToolCall(req: Request, store: Store, cfg: RelayConfig): Promise<Response> {
	const raw = await req.json().catch(() => null);
	const parsed = ToolCallBody.safeParse(raw);
	if (!parsed.success) {
		return jsonResponse({ error: "invalid body", issues: parsed.error.issues }, 400);
	}
	const { name, arguments: args, timeout_ms, stream } = parsed.data;

	const split = parseToolName(name);
	if (!split) {
		return jsonResponse({
			ok: false,
			content: [{ type: "text", text: `error: tool name must be '<label>__<tool>' (got '${name}')` }],
		}, 200);
	}
	const machine = store.listOnlineMachines().find((m) => m.id === split.label);
	if (!machine) {
		return jsonResponse({
			ok: false,
			content: [{ type: "text", text: `error: no online machine with HWID '${split.label}'` }],
		}, 200);
	}

	const callId = `t_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
	const timeoutMs = timeout_ms ?? 30_000;
	const { promise, resolve, reject } = Promise.withResolvers<ToolResultFrame>();
	const pending: PendingCall = {
		id: callId,
		name: split.tool,
		args: args ?? {},
		timeoutMs,
		resolve,
		reject,
		timer: undefined,
	};
	pending.timer = setTimeout(() => {
		pending.reject(new Error(`tool call timed out after ${timeoutMs}ms`));
		machine.pendingCalls.delete(callId);
		try {
			(machine.ws as { send?: (s: string) => void }).send?.(JSON.stringify({ type: "tool.cancel", id: callId }));
		} catch {
			// ignore
		}
	}, timeoutMs);
	const ok = dispatchToolCall(store, machine.id, pending);
	if (!ok) {
		clearTimeout(pending.timer);
		if (stream) {
			const enc = new TextEncoder();
			const errSse = new ReadableStream<Uint8Array>({
				start(controller) {
					controller.enqueue(enc.encode(`event: result\ndata: ${JSON.stringify({
						ok: false,
						id: callId,
						content: [{ type: "text", text: "error: failed to dispatch to connector — machine went offline" }],
					})}\n\n`));
					try { controller.close(); } catch { /* ignore */ }
				},
			});
			return new Response(errSse, {
				headers: {
					"Content-Type": "text/event-stream",
					"Cache-Control": "no-cache, no-transform",
				},
			});
		}
		return jsonResponse({
			ok: false,
			content: [{ type: "text", text: "error: failed to dispatch to connector" }],
		}, 200);
	}
	// Forward client-side abort to the connector.
	const onAbort = () => {
		clearTimeout(pending.timer);
		machine.pendingCalls.delete(callId);
		try {
			(machine.ws as { send?: (s: string) => void }).send?.(JSON.stringify({ type: "tool.cancel", id: callId }));
		} catch {
			// ignore
		}
		pending.reject(new Error("client aborted"));
	};
	if (req.signal.aborted) {
		onAbort();
	} else {
		req.signal.addEventListener("abort", onAbort, { once: true });
	}

	if (stream) {
		const enc = new TextEncoder();
		const sse = new ReadableStream<Uint8Array>({
			start(controller) {
				const send = (event: string, data: unknown) => {
					try {
						controller.enqueue(enc.encode(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`));
					} catch {
						// stream closed
					}
				};
				send("started", { id: callId, name: split.tool, machine: machine.label });
				pending.onProgress = (delta) => send("progress", { id: callId, delta });
				promise.then((frame) => {
					send("result", {
						id: callId,
						ok: frame.ok,
						content: frame.content ?? [],
						error: frame.error,
						duration_ms: frame.duration_ms,
					});
					try { controller.close(); } catch { /* ignore */ }
				}).catch((err: unknown) => {
					send("result", {
						id: callId,
						ok: false,
						content: [{ type: "text", text: `error: ${err instanceof Error ? err.message : String(err)}` }],
					});
					try { controller.close(); } catch { /* ignore */ }
				});
			},
			cancel() {
				onAbort();
			},
		});
		return new Response(sse, {
			headers: {
				"Content-Type": "text/event-stream",
				"Cache-Control": "no-cache, no-transform",
			},
		});
	}

	try {
		const frame = await promise;
		return jsonResponse({
			ok: frame.ok,
			content: frame.content ?? [],
			error: frame.error,
			duration_ms: frame.duration_ms,
		});
	} catch (e) {
		return jsonResponse({
			ok: false,
			content: [{ type: "text", text: `error: ${e instanceof Error ? e.message : String(e)}` }],
		}, 200);
	}
}

function handleEventsStream(req: Request, store: Store): Response {
	const enc = new TextEncoder();
	let cleanup: (() => void) | null = null;
	const stream = new ReadableStream<Uint8Array>({
		start(controller) {
			const send = (data: object) => {
				try {
					controller.enqueue(enc.encode(`data: ${JSON.stringify(data)}\n\n`));
				} catch {
					// stream closed
				}
			};
			send({
				type: "snapshot",
				machines: store.listMachines().map((m) => ({
					id: m.id,
					label: m.label,
					status: m.status,
					hostname: m.hostname,
					os: m.os,
					arch: m.arch,
					capabilities: m.capabilities,
				})),
			});
			const unsub = store.onMachinesChange((reason, id) => {
				const m = id ? store.getMachine(id) : undefined;
				send({
					type: "change",
					reason,
					id,
					machine: m
						? { id: m.id, label: m.label, status: m.status, hostname: m.hostname, os: m.os, arch: m.arch, capabilities: m.capabilities }
						: null,
				});
			});
			const interval = setInterval(() => {
				try {
					controller.enqueue(enc.encode(": keepalive\n\n"));
				} catch {
					// closed
				}
			}, 15000);
			cleanup = () => {
				clearInterval(interval);
				unsub();
				try {
					controller.close();
				} catch {
					// already closed
				}
			};
			req.signal.addEventListener("abort", () => cleanup?.());
		},
		cancel() {
			cleanup?.();
		},
	});
	return new Response(stream, {
		headers: {
			"Content-Type": "text/event-stream",
			"Cache-Control": "no-cache, no-transform",
		},
	});
}
